name: E2E
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  Cypress-Run-Chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up Cypress
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: ./Week-10-cy-automation
      - name: Run Cypress tests
        run: npm run test:all:chrome
        working-directory: ./Week-10-cy-automation

  Cypress-Run-Firefox:
    runs-on: macos-latest
    name: E2E on Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Firefox
        run: brew install --cask firefox 
      - name: Set up Cypress
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: firefox
          working-directory: ./Week-10-cy-automation
      - name: Run Cypress tests
        run: npm run test:all:firefox
        working-directory: ./Week-10-cy-automation
  

