name: E2E

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run-Chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Cypress
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: ./Week-10-cy-automation

      - name: Run Cypress tests
        run: npm run test:all:chrome:report
        working-directory: ./Week-10-cy-automation

      - name: Check for report directory and merge
        run: |
          if [ -d "./cypress/reports/html/.jsons" ]; then
            npm run test:merge-reports-cicd-fail-chrome && npm run test:generate-report-cicd-fail-chrome
          else
            echo "Report directory does not exist. Skipping merge."
          fi
        working-directory: ./Week-10-cy-automation

      - name: Upload Mochawesome reports chrome
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-chrome
          path: |
            if [ -f "./cypress/reports/html/.jsons/merged-report-chrome.html" ]; then
              echo "./cypress/reports/html/.jsons/merged-report-chrome.html"
            else
              echo "./Week-10-cy-automation/mochawesome-report-chrome"
            fi

  

