name: E2E on Chrome
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./Week-10-cy-automation

      - name: Run Cypress tests
        run: npm run test:all:chrome
        working-directory: ./Week-10-cy-automation

      - name: Upload Mochawesome reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ./Week-10-cy-automation/mochawesome-report/
