name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    name: Run Cypress Tests on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Dependencies
        run: npm ci
        working-directory: ./Week-10-cy-automation
      - name: Export Environment Variable for Chrome
        run: echo "CYPRESS_REPORT_DIR=mochawesome-report-chrome" >> $GITHUB_ENV
      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: ./Week-10-cy-automation

  cypress-run-firefox:
    runs-on: ubuntu-latest
    name: Run Cypress Tests on Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Dependencies
        run: npm ci
        working-directory: ./Week-10-cy-automation
      - name: Export Environment Variable for Firefox
        run: echo "CYPRESS_REPORT_DIR=mochawesome-report-firefox" >> $GITHUB_ENV
      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: firefox
          working-directory: ./Week-10-cy-automation


  

